#!/usr/bin/env bash
--source data/silver/mix2.amr
--target data/silver/mix2.snt
--source-graphs data/silver/mix2.grh
--validation-source data/silver/test.amr
--validation-target data/silver/test.snt
--val-source-graphs data/silver/test.grh
--edge-vocab data/silver/edge_vocab.json
--batch-size 24
--batch-type sentence
--word-min-count 3:3
--num-embed 360:360
--embed-dropout .5:.5
--max-seq-len 159:159
--encoder gcn
--gcn-activation relu
--gcn-num-hidden 360
--gcn-pos-embed 360
--decoder rnn
--num-layers 1:2
--rnn-num-hidden 360
--rnn-decoder-hidden-dropout 0.2
--checkpoint-frequency 1500
--max-num-checkpoint-not-improved 28
--initial-learning-rate 0.0003
--learning-rate-reduce-factor 0.7
--learning-rate-reduce-num-not-improved 6
--gcn-num-layers 4
--weight-init-xavier-factor-type in
--weight-init-scale 2.34
--decode-and-evaluate -1
--output silver_model
--overwrite-output
--device-ids 0
--gcn-dropout 0.1
--gcn-adj-norm
--rnn-attention-type coverage
--shared-vocab
--weight-tying
--weight-tying-type src_trg