#!/usr/bin/env bash
python3 -m sockeye.train --source sockeye/data/amr_2017/train.amr \
        --target sockeye/data/amr_2017/train.snt \
        --source-graphs sockeye/data/amr_2017/train.grh \
        --validation-source sockeye/data/amr_2017/dev.amr \
        --validation-target sockeye/data/amr_2017/dev.snt \
        --val-source-graphs sockeye/data/amr_2017/dev.grh \
        --edge-vocab sockeye/data/amr_2017/edge_vocab.json \
        --batch-size 16 \
        --batch-type sentence \
        --word-min-count 2:2 \
        --num-embed 300:300 \
        --embed-dropout .5:.5 \
        --max-seq-len 199:199 \
        --encoder gcn \
        --gcn-activation relu \
        --gcn-num-hidden 360 \
        --gcn-pos-embed 300 \
        --decoder rnn \
        --num-layers 3:1 \
        --rnn-num-hidden 300 \
        --rnn-decoder-hidden-dropout 0.2 \
        --checkpoint-frequency 1000 \
        --max-num-checkpoint-not-improved 27 \
        --initial-learning-rate 0.0003 \
        --learning-rate-reduce-factor 0.7 \
        --learning-rate-reduce-num-not-improved 5 \
        --gcn-num-layers 3 \
        --weight-init-xavier-factor-type in \
        --weight-init-scale 2.34 \
        --decode-and-evaluate -1 \
        --output sockeye/amr2017_model \
        --overwrite-output \
        --device-ids 1 \
        --gcn-dropout 0.1 \
        --gcn-adj-norm \
        --rnn-attention-type coverage \
        --shared-vocab \
        --weight-tying \
        --weight-tying-type src_trg \
        --seed 7